spring:
  # DATASOURCE CONFIG
  datasource:
      url: "jdbc:mysql://localhost:3306/drone"
      username: "root"
      password: "password"
      driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA CONFIG
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect